theme: jekyll-theme-cayman
url: https://coronasurveys.org
title: <img src="{{ 'assets/coronasurveys_logo.png' | relative_url }}">
       <br>
      <h1 class="main-title"><span>&#64;</span>CoronaSurveys<span>&#58;</span> Monitoring the Incidence of COVID-19 via Open Surveys </h1>  
github:
  is_project_page: false

plugins:
- github-pages
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-seo-tag
