theme: jekyll-theme-cayman
title: <a href="http://www.zina-studio.com/">
         <img src="https://raw.githubusercontent.com/AugustoGarcia/Coronasurveys-web/master/assets/logo.jpg" 
         height="100" width="200" style="text-align:left">
      </a> 
      <font size="5"> <span>&#64;</span>CoronaSurveys<span>&#58;</span> Monitoring the Incidence of COVID-19 via Anonymous Surveys </font>
description:  
         The CoronaSurveys project is a collaborative endeavour from several universities and research institutes 
         <a href="https://gcgimdea.github.io/Coronasurveys-web/info/team/" style="color:white"> (<u>team members</u>)</a>. 
         Results present our estimations on the incidence of COVID-19 in the countries from which we have enough information. 
         You can help by regularly completing the survey below.
         <br><br>
         
github:
  is_project_page: false
