theme: jekyll-theme-cayman
url: https://coronasurveys.org
title: Coronasurveys - International survey on coronavirus incidence.
tagline: Monitoring the Incidence of Coronavirus (COVID-19) via open surveys.
description: An international group monitoring the incidence of Coronavirus (Covid-19) through anonymous surveys. Data collected is made public. Participate and assist in the efforts. 
github:
  is_project_page: false

plugins:
- github-pages
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-seo-tag
