theme: jekyll-theme-cayman
url: https://coronasurveys.org
title: @CoronaSurveys: Monitoring the Incidence of COVID-19 via Open Surveys 
github:
  is_project_page: false

plugins:
- github-pages
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-seo-tag
