theme: jekyll-theme-cayman
url: https://coronasurveys.org
title: Coronavirus Survey to monitor disease incidence
tagline: Monitoring the Incidence of Coronavirus (COVID-19) via open surveys.
description: Coronavirus Survey. Coronasurveys is an international group monitoring the incidence of Coronavirus (Covid-19, Sars-Cov-2) through anonymous surveys. 
github:
  is_project_page: false

plugins:
- github-pages
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-seo-tag
