theme: jekyll-theme-cayman
url: https://coronasurveys.org
title: <a href="http://www.zina-studio.com/">
         <img src="https://raw.githubusercontent.com/GCGImdea/coronasurveys/master/artwork/quixote_fights_corona.jpg" 
         height="100" width="200" style="text-align:left">
      </a> <br>
      <font size="5"> <span>&#64;</span>CoronaSurveys<span>&#58;</span> Monitoring the Incidence of COVID-19 via Open Surveys </font>
description:
         <a href="https://www.networks.imdea.org/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/imdea-networks-positivo-color.jpg" height="50" width="100">
         </a> 
         <a href="https://www.ucy.ac.cy/en/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/University_of_Cyprus_2gr.jpg" height="50" width="150">
         </a> 
         <a href="https://www.algolysis.com/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/algolysis_corporate-identity_v4.0-Grayscale_LOGO-dark-on-white-text-right.jpg" height="50" width="150">
         </a> 
         <a href="https://viterbischool.usc.edu/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/Formal_Viterbi_CardOnWhite.jpg" height="50" width="130">
         </a> 
         <a href="https://www.tu-darmstadt.de/index.en.jsp">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/tud_logo.png" height="50" width="120">
         </a> 
         <a href="https://www.tuat.ac.jp/en/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/tat_2.png" height="50" width="100">
         </a> 
         <a href="https://www.ed.ac.uk/informatics">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/InformaticsUni_transparent.gif" height="50" width="180">
         </a> 
         <a href="https://www.uminho.pt/EN">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/UMinho.png" height="50" width="100">
         </a> 
         <a href="https://www.inesctec.pt/en">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/inesctec.png" height="50" width="50">
         </a> 
         <a href="https://www.unitn.it/en/">
         <img src="https://github.com/GCGImdea/coronasurveys/raw/master/logos/newlogo_unitn_it.png" height="50" width="160">
         </a> 
      
         
github:
  is_project_page: false

plugins:
- github-pages
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
